"""cascading in user

Revision ID: 268bb23ec65c
Revises: 
Create Date: 2024-03-03 15:02:14.167748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268bb23ec65c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_data_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_data_game_name'), ['game_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_data_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    with op.batch_alter_table('game_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_data_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_data_id'))
        batch_op.drop_index(batch_op.f('ix_game_data_game_name'))
        batch_op.drop_index(batch_op.f('ix_game_data_game_id'))

    # ### end Alembic commands ###
